/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author ADMIN
 */
public class JFrame_TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_TrangChu
     */
    private TrangChu trangChu;
    public JFrame_TrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuTaskBar = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        bar1 = new javax.swing.JPanel();
        bar2 = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        pnlIcon = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        lblNhanVien = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Icon1 = new javax.swing.JLabel();
        Content1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Icon2 = new javax.swing.JLabel();
        Content2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Icon3 = new javax.swing.JLabel();
        Content3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Icon4 = new javax.swing.JLabel();
        Content4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Icon5 = new javax.swing.JLabel();
        Content5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        Icon6 = new javax.swing.JLabel();
        Content6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        bar3 = new javax.swing.JPanel();
        pnlBottom = new javax.swing.JPanel();
        Icon7 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        nutDangXuat = new javax.swing.JButton();
        bar4 = new javax.swing.JPanel();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lý đặt phòng khách sạn");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(250, 250, 250));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusableWindowState(false);
        setForeground(java.awt.Color.white);
        setSize(new java.awt.Dimension(1400, 800));

        MenuTaskBar.setBackground(new java.awt.Color(250, 250, 250));
        MenuTaskBar.setPreferredSize(new java.awt.Dimension(250, 1400));
        MenuTaskBar.setLayout(new java.awt.BorderLayout());

        pnlTop.setBackground(new java.awt.Color(250, 250, 250));
        pnlTop.setPreferredSize(new java.awt.Dimension(250, 80));
        pnlTop.setLayout(new java.awt.BorderLayout());

        bar1.setBackground(new java.awt.Color(204, 214, 219));
        bar1.setOpaque(false);
        bar1.setPreferredSize(new java.awt.Dimension(1, 0));

        javax.swing.GroupLayout bar1Layout = new javax.swing.GroupLayout(bar1);
        bar1.setLayout(bar1Layout);
        bar1Layout.setHorizontalGroup(
            bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bar1Layout.setVerticalGroup(
            bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlTop.add(bar1, java.awt.BorderLayout.EAST);

        bar2.setBackground(new java.awt.Color(204, 214, 219));
        bar2.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout bar2Layout = new javax.swing.GroupLayout(bar2);
        bar2.setLayout(bar2Layout);
        bar2Layout.setHorizontalGroup(
            bar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        bar2Layout.setVerticalGroup(
            bar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlTop.add(bar2, java.awt.BorderLayout.SOUTH);

        info.setOpaque(false);
        info.setLayout(new java.awt.BorderLayout());

        pnlIcon.setOpaque(false);
        pnlIcon.setPreferredSize(new java.awt.Dimension(60, 0));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        lblIcon.setPreferredSize(new java.awt.Dimension(50, 70));
        pnlIcon.add(lblIcon);

        info.add(pnlIcon, java.awt.BorderLayout.WEST);

        pnlInfo.setBackground(new java.awt.Color(250, 250, 250));
        pnlInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 0, 0));
        pnlInfo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        lblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNhanVien.setText("Nguyễn Tiến Đạt");
        pnlInfo.add(lblNhanVien);

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblChucVu.setText("Quản lý");
        pnlInfo.add(lblChucVu);

        info.add(pnlInfo, java.awt.BorderLayout.CENTER);

        pnlTop.add(info, java.awt.BorderLayout.CENTER);

        MenuTaskBar.add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlCenter.setBackground(new java.awt.Color(250, 250, 250));
        pnlCenter.setToolTipText("");
        pnlCenter.setPreferredSize(new java.awt.Dimension(230, 600));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        jScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 0, 10));
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(225, 45));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 7));

        Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sucess.png"))); // NOI18N
        Icon1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        Icon1.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel1.add(Icon1);

        Content1.setPreferredSize(new java.awt.Dimension(155, 50));
        Content1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Content1MousePressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(250, 250, 250));
        jButton1.setText("Trang Chủ");

        javax.swing.GroupLayout Content1Layout = new javax.swing.GroupLayout(Content1);
        Content1.setLayout(Content1Layout);
        Content1Layout.setHorizontalGroup(
            Content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        Content1Layout.setVerticalGroup(
            Content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Content1);

        Icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sucess.png"))); // NOI18N
        Icon2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        Icon2.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel1.add(Icon2);

        Content2.setPreferredSize(new java.awt.Dimension(155, 50));

        jButton2.setBackground(new java.awt.Color(250, 250, 250));
        jButton2.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout Content2Layout = new javax.swing.GroupLayout(Content2);
        Content2.setLayout(Content2Layout);
        Content2Layout.setHorizontalGroup(
            Content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        Content2Layout.setVerticalGroup(
            Content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Content2);

        Icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sucess.png"))); // NOI18N
        Icon3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        Icon3.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel1.add(Icon3);

        Content3.setPreferredSize(new java.awt.Dimension(155, 50));

        jButton3.setBackground(new java.awt.Color(250, 250, 250));
        jButton3.setText("Quản Lý Khách Hàng");

        javax.swing.GroupLayout Content3Layout = new javax.swing.GroupLayout(Content3);
        Content3.setLayout(Content3Layout);
        Content3Layout.setHorizontalGroup(
            Content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        Content3Layout.setVerticalGroup(
            Content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Content3);

        Icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sucess.png"))); // NOI18N
        Icon4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        Icon4.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel1.add(Icon4);

        Content4.setPreferredSize(new java.awt.Dimension(155, 50));
        Content4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Content4MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(250, 250, 250));
        jButton4.setText("Quản Lý Đồ Ăn Uống");

        javax.swing.GroupLayout Content4Layout = new javax.swing.GroupLayout(Content4);
        Content4.setLayout(Content4Layout);
        Content4Layout.setHorizontalGroup(
            Content4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        Content4Layout.setVerticalGroup(
            Content4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Content4);

        Icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sucess.png"))); // NOI18N
        Icon5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        Icon5.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel1.add(Icon5);

        Content5.setPreferredSize(new java.awt.Dimension(155, 50));

        jButton5.setBackground(new java.awt.Color(250, 250, 250));
        jButton5.setText("Quản Lý Phòng");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Content5Layout = new javax.swing.GroupLayout(Content5);
        Content5.setLayout(Content5Layout);
        Content5Layout.setHorizontalGroup(
            Content5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        Content5Layout.setVerticalGroup(
            Content5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Content5);

        Icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sucess.png"))); // NOI18N
        Icon6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        Icon6.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel1.add(Icon6);

        Content6.setPreferredSize(new java.awt.Dimension(155, 50));

        jButton6.setBackground(new java.awt.Color(250, 250, 250));
        jButton6.setText("Thống Kê");

        javax.swing.GroupLayout Content6Layout = new javax.swing.GroupLayout(Content6);
        Content6.setLayout(Content6Layout);
        Content6Layout.setHorizontalGroup(
            Content6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        Content6Layout.setVerticalGroup(
            Content6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Content6);

        jScrollPane.setViewportView(jPanel1);

        pnlCenter.add(jScrollPane, java.awt.BorderLayout.CENTER);

        MenuTaskBar.add(pnlCenter, java.awt.BorderLayout.CENTER);

        bar3.setBackground(new java.awt.Color(204, 214, 219));
        bar3.setPreferredSize(new java.awt.Dimension(1, 1));
        bar3.setLayout(new java.awt.BorderLayout());
        MenuTaskBar.add(bar3, java.awt.BorderLayout.EAST);

        pnlBottom.setBackground(new java.awt.Color(250, 250, 250));
        pnlBottom.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlBottom.setLayout(new java.awt.BorderLayout());

        Icon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sucess.png"))); // NOI18N
        Icon7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        Icon7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlBottom.add(Icon7, java.awt.BorderLayout.LINE_START);

        DangXuat.setPreferredSize(new java.awt.Dimension(200, 30));

        nutDangXuat.setBackground(new java.awt.Color(250, 250, 250));
        nutDangXuat.setText("Đăng xuất");

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nutDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nutDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBottom.add(DangXuat, java.awt.BorderLayout.CENTER);

        bar4.setBackground(new java.awt.Color(204, 214, 219));
        bar4.setPreferredSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout bar4Layout = new javax.swing.GroupLayout(bar4);
        bar4.setLayout(bar4Layout);
        bar4Layout.setHorizontalGroup(
            bar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        bar4Layout.setVerticalGroup(
            bar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlBottom.add(bar4, java.awt.BorderLayout.EAST);

        MenuTaskBar.add(pnlBottom, java.awt.BorderLayout.SOUTH);

        getContentPane().add(MenuTaskBar, java.awt.BorderLayout.WEST);

        MainContent.setBackground(new java.awt.Color(250, 250, 250));
        MainContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(MainContent, java.awt.BorderLayout.CENTER);
        trangChu = new TrangChu();
        MainContent.add(trangChu).setVisible(true);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Content1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Content1MousePressed

       
    }//GEN-LAST:event_Content1MousePressed

    private void Content4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Content4MouseClicked

    }//GEN-LAST:event_Content4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content1;
    private javax.swing.JPanel Content2;
    private javax.swing.JPanel Content3;
    private javax.swing.JPanel Content4;
    private javax.swing.JPanel Content5;
    private javax.swing.JPanel Content6;
    private javax.swing.JPanel DangXuat;
    private javax.swing.JLabel Icon1;
    private javax.swing.JLabel Icon2;
    private javax.swing.JLabel Icon3;
    private javax.swing.JLabel Icon4;
    private javax.swing.JLabel Icon5;
    private javax.swing.JLabel Icon6;
    private javax.swing.JLabel Icon7;
    private javax.swing.JPanel MainContent;
    private javax.swing.JPanel MenuTaskBar;
    private javax.swing.JPanel bar1;
    private javax.swing.JPanel bar2;
    private javax.swing.JPanel bar3;
    private javax.swing.JPanel bar4;
    private javax.swing.JPanel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JButton nutDangXuat;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlIcon;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
