/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import connectDB.ConnectDB;
import java.sql.SQLException;

/**
 *
 * @author ASUS
 */
public class JFrame_Login extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Login
     * @throws java.lang.Exception
     */
    public JFrame_Login() throws Exception {
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_dangNhap = new javax.swing.JLabel();
        txt_quenMatKhau = new javax.swing.JLabel();
        btn_dangNhap = new javax.swing.JButton();
        txt_matKhau = new javax.swing.JLabel();
        input_password = new javax.swing.JPasswordField();
        input_tenNhanVien = new javax.swing.JTextField();
        txt_tenNhanVien = new javax.swing.JLabel();
        UI_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        txt_dangNhap.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        txt_dangNhap.setForeground(new java.awt.Color(255, 255, 255));
        txt_dangNhap.setText("Đăng nhập");
        jPanel1.add(txt_dangNhap);
        txt_dangNhap.setBounds(140, 220, 290, 66);

        txt_quenMatKhau.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        txt_quenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        txt_quenMatKhau.setText("Quên mật khẩu?");
        jPanel1.add(txt_quenMatKhau);
        txt_quenMatKhau.setBounds(200, 560, 160, 40);

        btn_dangNhap.setBackground(new java.awt.Color(51, 153, 255));
        btn_dangNhap.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_dangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangNhap.setText("Đăng nhập");
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dangNhap);
        btn_dangNhap.setBounds(120, 510, 300, 50);

        txt_matKhau.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txt_matKhau.setForeground(new java.awt.Color(255, 255, 255));
        txt_matKhau.setText("Mật khẩu:");
        jPanel1.add(txt_matKhau);
        txt_matKhau.setBounds(120, 410, 160, 40);

        input_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(input_password);
        input_password.setBounds(250, 410, 220, 40);
        jPanel1.add(input_tenNhanVien);
        input_tenNhanVien.setBounds(250, 340, 220, 40);

        txt_tenNhanVien.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txt_tenNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        txt_tenNhanVien.setText("Tên nhân viên:");
        jPanel1.add(txt_tenNhanVien);
        txt_tenNhanVien.setBounds(80, 340, 160, 40);

        UI_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/screen_Login.png"))); // NOI18N
        jPanel1.add(UI_login);
        UI_login.setBounds(0, 0, 940, 788);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_passwordActionPerformed

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrame_Login().setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UI_login;
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JPasswordField input_password;
    private javax.swing.JTextField input_tenNhanVien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_dangNhap;
    private javax.swing.JLabel txt_matKhau;
    private javax.swing.JLabel txt_quenMatKhau;
    private javax.swing.JLabel txt_tenNhanVien;
    // End of variables declaration//GEN-END:variables
}
