package gui;

import javax.swing.*;

public class JFrame_loading extends javax.swing.JPanel {

    private JDialog dialog;
    private JProgressBar loadingBar;

    /**
     * Creates new form JFrame_loading
     */
    public JFrame_loading() {
        initComponents();
        dialog = createDialog();
    }

    private JDialog createDialog() {
        JDialog loadingDialog = new JDialog();
        loadingDialog.setUndecorated(true);
        loadingDialog.add(this);
        loadingBar = new JProgressBar();
        loadingBar.setIndeterminate(true); // Set the loading bar to indeterminate mode
        loadingBar.setPreferredSize(new java.awt.Dimension(200, 8)); // Set preferred size
        loadingDialog.add(loadingBar, java.awt.BorderLayout.SOUTH); // Add the loading bar to the bottom
        loadingDialog.pack();
        loadingDialog.setLocationRelativeTo(null); // Center the dialog on the screen
        return loadingDialog;
    }

    public void showLoadingScreen() {
        dialog.setVisible(true);
    }

    public void hideLoadingScreen() {
        dialog.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loading_ver2.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
