/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import connectDB.ConnectDB;
import dao.HoaDon_DAO;
import entity.HoaDon;
import entity.NhanVien;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M S I
 */
public class JPanel_QuanLyHoaDon extends javax.swing.JPanel implements ActionListener {

    private HoaDon_DAO hd_DAO;
    private NhanVien nv;

    /**
     * Creates new form JPanel_QuanLyNhanVien
     */
    public JPanel_QuanLyHoaDon(NhanVien nhanVien) throws SQLException {
        initComponents();
        this.nv = nhanVien;
        if (!nv.isChucVu()) {
            AllListHoaDonbyNhanVien();
        } else {
            AllListHoaDon();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hoaDon = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        search_Engine = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(931, 800));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tbl_hoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Khách hàng", "Khuyến mãi", "Nhân viên", "Ngày lập hóa đơn", "Thuế", "Tổng tiền ban đầu", "Tổng tiền phải trả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_hoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_hoaDon);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel11.setBackground(new java.awt.Color(51, 255, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Danh Sách Thông Tin Hóa Đơn");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setMaximumSize(new java.awt.Dimension(270, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(270, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(265, 25));
        jPanel3.add(jLabel11, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        search_Engine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search_Engine.setLayout(new javax.swing.BoxLayout(search_Engine, javax.swing.BoxLayout.X_AXIS));
        add(search_Engine, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_hoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_hoaDonMouseClicked

    private void AllListHoaDon() throws SQLException {
        tbl_hoaDon.removeAll();
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        hd_DAO = new HoaDon_DAO();
        ArrayList<HoaDon> listHD = hd_DAO.getAllTableHoaDon();

        if (tbl_hoaDon.getModel() == null) {
            String[] arr = {"Mã hóa đơn", "Khách hàng", "Khuyến mãi", "Nhân viên", "Ngày lập hóa đơn", "Thuế", "Tổng số tiền ban đầu", "Tổng số tiền phải trả"};
            DefaultTableModel modelHoaDon = new DefaultTableModel(arr, 0);
            tbl_hoaDon.setModel(modelHoaDon);
        }
        DefaultTableModel model = (DefaultTableModel) tbl_hoaDon.getModel();
        model.setRowCount(0);

        for (HoaDon hd : listHD) {
            System.out.println("hd.getKhachHang().getHoTenKhachHang(): " + hd.getKhachHang().getHoTenKhachHang());
            if (hd.getTongThanhTienBanDau() != 0) {
                model.addRow(new Object[]{hd.getMaHoaDon(), hd.getKhachHang().getMaKhachHang(), hd.getKhuyenMai().getMaKhuyenMai(), hd.getNhanVien().getMaNhanVien(),
                    hd.getNgayLapHoaDon(), hd.getThue(), hd.getTongThanhTienBanDau(), hd.getTongThanhTienPhaiTra()});
            }
        }
    }

    private void AllListHoaDonbyNhanVien() throws SQLException {
        tbl_hoaDon.removeAll();
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        hd_DAO = new HoaDon_DAO();
        ArrayList<HoaDon> listHD = hd_DAO.getAllTableHoaDon();

        if (tbl_hoaDon.getModel() == null) {
            String[] arr = {"Mã hóa đơn", "Khách hàng", "Khuyến mãi", "Nhân viên", "Ngày lập hóa đơn", "Thuế", "Tổng số tiền ban đầu", "Tổng số tiền phải trả"};
            DefaultTableModel modelHoaDon = new DefaultTableModel(arr, 0);
            tbl_hoaDon.setModel(modelHoaDon);
        }
        DefaultTableModel model = (DefaultTableModel) tbl_hoaDon.getModel();
        model.setRowCount(0);

        for (HoaDon hd : listHD) {
            if (hd.getTongThanhTienBanDau() != 0 && hd.getNhanVien().getMaNhanVien().equals(this.nv.getMaNhanVien())) {
                model.addRow(new Object[]{hd.getMaHoaDon(), hd.getKhachHang().getMaKhachHang(), hd.getKhuyenMai().getMaKhuyenMai(), hd.getNhanVien().getMaNhanVien(),
                    hd.getNgayLapHoaDon(), hd.getThue(), hd.getTongThanhTienBanDau(), hd.getTongThanhTienPhaiTra()});
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel search_Engine;
    private javax.swing.JTable tbl_hoaDon;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object o = e.getSource();
    }

}
