/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import connectDB.ConnectDB;
import dao.KhachHang_DAO;
import entity.KhachHang;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class JPanel_ThemKHNhanh extends javax.swing.JPanel {
    
    /**
     * Creates new form JPanel_ThemKHNhanh
     */
    private KhachHang_DAO kh_dao = new KhachHang_DAO();
    public JPanel_ThemKHNhanh() {
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
        }
        initComponents();
    }
    public KhachHang taoKH() {
        String ma = txt_MaKH.getText().toString();
        String ten = txt_Ten.getText().toString();
        String email = txt_email.getText().toString();
        boolean gioiTinh = rd_nam.isSelected();
        String cccd = txt_CCCD.getText().toString();
        LocalDate ngaySinh = convertToLocalDate(btn_ngaySinh.getDate());
        boolean trangThai = rd_bt.isSelected();
        
        return new KhachHang(ma, ten, email, gioiTinh, cccd, ngaySinh, trangThai);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frm_ThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_CCCD = new javax.swing.JTextField();
        txt_MaKH = new javax.swing.JTextField();
        txt_Ten = new javax.swing.JTextField();
        rd_nu = new javax.swing.JRadioButton();
        rd_nam = new javax.swing.JRadioButton();
        rd_dsd = new javax.swing.JRadioButton();
        rd_bt = new javax.swing.JRadioButton();
        btn_ngaySinh = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btn_Rong = new javax.swing.JButton();

        frm_ThongTin.setPreferredSize(new java.awt.Dimension(350, 0));

        jLabel1.setText("SĐT:");

        jLabel2.setText("Giới tính:");

        jLabel6.setText("Tên:");

        jLabel7.setText("CCCD:");

        jLabel8.setText("Ngày sinh:");

        jLabel9.setText("Trạng Thái:");

        rd_nu.setText("Nữ");

        rd_nam.setText("Nam");
        rd_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_namActionPerformed(evt);
            }
        });

        rd_dsd.setText("Danh sách đen");

        rd_bt.setText("Bình thường");
        rd_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_btActionPerformed(evt);
            }
        });

        btn_ngaySinh.setDateFormatString("dd-MM-yyyy");

        jLabel10.setText("Email:");

        javax.swing.GroupLayout frm_ThongTinLayout = new javax.swing.GroupLayout(frm_ThongTin);
        frm_ThongTin.setLayout(frm_ThongTinLayout);
        frm_ThongTinLayout.setHorizontalGroup(
            frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_ThongTinLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frm_ThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(frm_ThongTinLayout.createSequentialGroup()
                            .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(frm_ThongTinLayout.createSequentialGroup()
                                    .addComponent(rd_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(rd_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_Ten)
                                .addComponent(txt_MaKH)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_ThongTinLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(frm_ThongTinLayout.createSequentialGroup()
                            .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(frm_ThongTinLayout.createSequentialGroup()
                                    .addComponent(rd_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(rd_dsd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btn_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(16, 16, 16))
        );
        frm_ThongTinLayout.setVerticalGroup(
            frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_nu)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_nam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_CCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_dsd)
                    .addComponent(rd_bt)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(350, 160));

        btnThem.setText("Thêm");
        btnThem.setToolTipText("");
        btnThem.setBackground(new Color(0, 102, 102));
        btnThem.setForeground(Color.WHITE);
        btnThem.setFont(new Font("Roboto Mono Medium", Font.PLAIN, 16));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btn_Rong.setText("Xóa rỗng");
        btn_Rong.setBackground(new Color(0, 102, 102));
        btn_Rong.setForeground(Color.WHITE);
        btn_Rong.setFont(new Font("Roboto Mono Medium", Font.PLAIN, 16));
        btn_Rong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_Rong, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Rong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(frm_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(frm_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rd_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_namActionPerformed

    private void rd_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_btActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (kiemTraCuPhap()) {
                KhachHang kh = taoKH();
                try {
//                    String imagePath_relative = "/gui/emp_pic/" + nv.getMaNhanVien() + ".png";
//                    nv.setHinhAnh("/gui/emp_pic/" + nv.getMaNhanVien() + ".png");
                    if(kh_dao.createKhachHang(kh)){
                        JOptionPane.showMessageDialog(null, "Thêm thành công");
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(JPanel_QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_btnThemActionPerformed
    
    private void btn_RongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RongActionPerformed
        // TODO add your handling code here:       
        txt_MaKH.setText("");
        txt_Ten.setText("");
        rd_nam.setSelected(true);
        txt_CCCD.setText("");
        rd_bt.setSelected(true);
        btn_ngaySinh.setDate(null);
      
    }//GEN-LAST:event_btn_RongActionPerformed

    private LocalDate convertToLocalDate(Date date) {
        return date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    public boolean kiemTraCuPhap() {
        LocalDate now = LocalDate.now();
        LocalDate ngaySinh = convertToLocalDate(btn_ngaySinh.getDate());
        String sdt = txt_MaKH.getText().trim();
        if (txt_Ten.getText().isEmpty() || !txt_Ten.getText().matches("^([\\p{L}\\s']{2,})+([\\p{L}\\s']{2,})$")) {
            JOptionPane.showMessageDialog(this, "\"Tên phải viết hoa với mỗi kí tự đầu tiên và không chứa số hoặc kí tự đặc biệt\"");
            return false;
        }
        if(txt_CCCD.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "CCCD Không được để trống");
        } else if(!txt_CCCD.getText().trim().matches("^\\d{12}$")){
            JOptionPane.showMessageDialog(this, "CCCD chỉ có 12 kí tự số");
			txt_CCCD.requestFocus();
			return false;
        }
        if(btn_ngaySinh.getDateFormatString().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để ngày sinh trống");
            return false;
        } else if (now.getYear() - ngaySinh.getYear() <= 17){
            JOptionPane.showMessageDialog(this, "Tuổi phải trên 18");
            return false;
        }
        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để số điện thoại trống");
            txt_MaKH.requestFocus();
            return false;
        } else if (!sdt.matches("^0\\d{9}$")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại chỉ có 10 kí tự số và bắt đầu bằng số 0");
            txt_MaKH.requestFocus();
            return false;
        }
        
//        LocalDate ngaySinh = convertToLocalDate(btn_ngaySinh.getDate());
//        String ngaySinhBangChu = btn_ngaySinh.getDateFormatString();
//        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
//        if (btn_ngaySinh.getDate() == null) {
//			JOptionPane.showMessageDialog(this, "Không được để ngày sinh trống");
//			return false;
//		} else if (LocalDate.now().getYear() - LocalDate.parse(ngaySinhBangChu, formatter).getYear() <= 17) {
//			JOptionPane.showMessageDialog(this, "Tuổi phải trên 18");
//			return false;
//		}
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btn_Rong;
    private com.toedter.calendar.JDateChooser btn_ngaySinh;
    private javax.swing.JPanel frm_ThongTin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rd_bt;
    private javax.swing.JRadioButton rd_dsd;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nu;
    private javax.swing.JTextField txt_CCCD;
    public javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_Ten;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables

}
