/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.border.TitledBorder;
/**
 *
 * @author ADMIN
 */
public class JPanelThanhToanDatPhong extends javax.swing.JPanel {

    /**
     * Creates new form JPanelThanhToanDatPhong
     */
    public JPanelThanhToanDatPhong() {
        initComponents();
    }
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("Thanh Toán Hóa Đơn");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                JPanelThanhToanDatPhong panel = new JPanelThanhToanDatPhong();
                frame.add(panel);
                frame.setLocationRelativeTo(null);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Header = new javax.swing.JLabel();
        lbl_SDT = new javax.swing.JLabel();
        lbl_NgayLapHD = new javax.swing.JLabel();
        pnl_CTHD = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_CTHD = new javax.swing.JTable();
        lbl_GiaTri = new javax.swing.JLabel();
        btn_Chon = new javax.swing.JButton();
        lbl_TongTienPhaiTra = new javax.swing.JLabel();
        lbl_KhuyenMai = new javax.swing.JLabel();
        lbl_Thue = new javax.swing.JLabel();
        lbl_TongTienBanDau = new javax.swing.JLabel();
        lbl_KhachHang = new javax.swing.JLabel();
        lbl_NhanVien = new javax.swing.JLabel();
        btn_HuyBo = new javax.swing.JButton();
        btn_XacNhanThanhToan = new javax.swing.JButton();
        btn_LuuTam = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(100, 30));
        setPreferredSize(new java.awt.Dimension(1010, 400));
        setLayout(null);

        lbl_Header.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Header.setText("Thông tin hóa đơn");
        add(lbl_Header);
        lbl_Header.setBounds(0, 0, 1010, 25);

        lbl_SDT.setText("Số điện thoại: 00000000000");
        add(lbl_SDT);
        lbl_SDT.setBounds(20, 80, 220, 30);

        lbl_NgayLapHD.setText("Ngày lập hóa đơn:");
        add(lbl_NgayLapHD);
        lbl_NgayLapHD.setBounds(770, 80, 220, 30);

        tbl_CTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
            },
            new String [] {
                "STT", "Tên dịch vụ", "Số lượng khách", "Ngày nhận phòng", "Ngày trả phòng", "Đơn vị","Đơn Giá", "Phụ Phí", "Thành Tiền"
            }
        ));
        jScrollPane1.setViewportView(tbl_CTHD);

        pnl_CTHD.setBorder(new TitledBorder(null, "Chi tiết hóa đơn"));

        javax.swing.GroupLayout pnl_CTHDLayout = new javax.swing.GroupLayout(pnl_CTHD);
        pnl_CTHD.setLayout(pnl_CTHDLayout);
        pnl_CTHDLayout.setHorizontalGroup(
            pnl_CTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_CTHDLayout.setVerticalGroup(
            pnl_CTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CTHDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );

        add(pnl_CTHD);
        pnl_CTHD.setBounds(10, 110, 990, 120);

        lbl_GiaTri.setText("Giá trị:");
        add(lbl_GiaTri);
        lbl_GiaTri.setBounds(20, 270, 140, 20);

        btn_Chon.setText("Chọn");
        btn_Chon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonActionPerformed(evt);
            }
        });
        add(btn_Chon);
        btn_Chon.setBounds(160, 240, 72, 20);

        lbl_TongTienPhaiTra.setText("Tổng tiền phải trả:");
        add(lbl_TongTienPhaiTra);
        lbl_TongTienPhaiTra.setBounds(360, 300, 200, 20);

        lbl_KhuyenMai.setText("Khuyến mãi:");
        add(lbl_KhuyenMai);
        lbl_KhuyenMai.setBounds(20, 240, 140, 20);

        lbl_Thue.setText("Thuế:");
        add(lbl_Thue);
        lbl_Thue.setBounds(360, 240, 200, 20);

        lbl_TongTienBanDau.setText("Tổng tiền ban đầu:");
        add(lbl_TongTienBanDau);
        lbl_TongTienBanDau.setBounds(360, 270, 200, 20);

        lbl_KhachHang.setText("Khách hàng: Nguyễn Tiến Đạt");
        add(lbl_KhachHang);
        lbl_KhachHang.setBounds(20, 50, 220, 30);

        lbl_NhanVien.setText("Nhân viên: Nguyễn Tiến Đạt");
        add(lbl_NhanVien);
        lbl_NhanVien.setBounds(770, 50, 220, 30);

        btn_HuyBo.setText("Hủy bỏ");
        btn_HuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyBoActionPerformed(evt);
            }
        });
        add(btn_HuyBo);
        btn_HuyBo.setBounds(820, 340, 180, 40);

        btn_XacNhanThanhToan.setText("Xác nhận thanh toán");
        btn_XacNhanThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanThanhToanActionPerformed(evt);
            }
        });
        add(btn_XacNhanThanhToan);
        btn_XacNhanThanhToan.setBounds(820, 240, 180, 40);

        btn_LuuTam.setText("Lưu tạm");
        btn_LuuTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuTamActionPerformed(evt);
            }
        });
        add(btn_LuuTam);
        btn_LuuTam.setBounds(820, 290, 180, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ChonActionPerformed

    private void btn_HuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_HuyBoActionPerformed

    private void btn_XacNhanThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XacNhanThanhToanActionPerformed

    private void btn_LuuTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LuuTamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Chon;
    private javax.swing.JButton btn_HuyBo;
    private javax.swing.JButton btn_LuuTam;
    private javax.swing.JButton btn_XacNhanThanhToan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_GiaTri;
    private javax.swing.JLabel lbl_Header;
    private javax.swing.JLabel lbl_KhachHang;
    private javax.swing.JLabel lbl_KhuyenMai;
    private javax.swing.JLabel lbl_NgayLapHD;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_Thue;
    private javax.swing.JLabel lbl_TongTienBanDau;
    private javax.swing.JLabel lbl_TongTienPhaiTra;
    private javax.swing.JPanel pnl_CTHD;
    private javax.swing.JTable tbl_CTHD;
    // End of variables declaration//GEN-END:variables
}
