/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import connectDB.ConnectDB;
import dao.Phong_DAO;
import entity.LoaiPhong;
import entity.Phong;
import entity.TrangThaiPhong;
import java.awt.Component;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author M S I
 */
public class JPanel_QuanLyPhongO extends javax.swing.JPanel implements ActionListener {

    private FileDialog fileDialog;
    private Phong_DAO ph_DAO;
    private DefaultTableModel modelPhong;

    /**
     * Creates new form JPanel_QuanLyNhanVien
     *
     * @throws java.sql.SQLException
     */
    public JPanel_QuanLyPhongO() throws SQLException {
        initComponents();
        addEvents();
        AllListPhong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_PhongO = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        frm_ThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_maPhong = new javax.swing.JTextField();
        txt_tenPhong = new javax.swing.JTextField();
        txt_dienTich = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_View = new javax.swing.JTextArea();
        cbo_LoaiPhong = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbo_soGiuong = new javax.swing.JComboBox<>();
        cbo_trangThaiPhong = new javax.swing.JComboBox<>();
        rad_coGiuongPhu = new javax.swing.JRadioButton();
        rad_khongGiuongPhu = new javax.swing.JRadioButton();
        rad_coHutThuoc = new javax.swing.JRadioButton();
        rad_khongHutThuoc = new javax.swing.JRadioButton();
        btn_chonAnh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoaRong = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        search_Engine = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(931, 800));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new java.awt.BorderLayout());

        String[] colHeader = {
            "Mã Phòng", "Tên Phòng", "Loại Phòng", "Trạng Thái Phòng", "Diện Tích Phòng", "Số Giường", "Giường Phụ", "View", "Hút Thuốc", "Hình Ảnh Phòng"
        };
        modelPhong = new DefaultTableModel(colHeader, 0);
        tbl_PhongO.setModel(modelPhong
        );
        tbl_PhongO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_PhongOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_PhongOMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_PhongO);
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        tbl_PhongO.getColumnModel().getColumn(1).setCellRenderer(leftRenderer);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i <= 8; i++) {
            if (i != 1) {
                tbl_PhongO.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
        }

        tbl_PhongO.getColumnModel().getColumn(9).setPreferredWidth(40);
        TableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {
                if (value instanceof ImageIcon) {
                    JLabel lbl = new JLabel((ImageIcon) value);
                    lbl.setHorizontalAlignment(JLabel.CENTER);
                    return lbl;
                }
                return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            }
        };
        tbl_PhongO.getColumnModel().getColumn(9).setCellRenderer(renderer);
        tbl_PhongO.setRowHeight(50);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel11.setBackground(new java.awt.Color(51, 255, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Danh Sách Thông Tin Phòng Ở Khách Sạn");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setMaximumSize(new java.awt.Dimension(270, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(270, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(265, 25));
        jPanel3.add(jLabel11, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        frm_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin phòng ở"));
        frm_ThongTin.setPreferredSize(new java.awt.Dimension(350, 0));

        jLabel1.setText("Mã Phòng:");

        jLabel2.setText("Trạng Thái Phòng:");

        jLabel6.setText("Tên Phòng:");

        jLabel7.setText("Loại Phòng:");

        jLabel8.setText("Giường Phụ");

        jLabel10.setText("Hút Thuốc: ");

        jLabel12.setText("Diện Tích Phòng:");

        jLabel14.setText("Hình ảnh:");

        jLabel16.setText("View:");

        txt_View.setColumns(20);
        txt_View.setRows(5);
        jScrollPane2.setViewportView(txt_View);

        cbo_LoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BASIC", "DOUBLE", "STANDARD", "BUSINESS","VIP" }));

        jLabel15.setText("Số giường:");

        cbo_soGiuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3"}));

        cbo_trangThaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "UNAVAILABLE", "BOOKED", "OCCUPIED" }));

        rad_coGiuongPhu.setText("Có");
        rad_coGiuongPhu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rad_coGiuongPhuMouseClicked(evt);
            }
        });

        rad_khongGiuongPhu.setText("Không");
        rad_khongGiuongPhu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rad_khongGiuongPhuMouseClicked(evt);
            }
        });

        rad_coHutThuoc.setText("Cho phép");
        rad_coHutThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rad_coHutThuocMouseClicked(evt);
            }
        });

        rad_khongHutThuoc.setText("Không");
        rad_khongHutThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rad_khongHutThuocMouseClicked(evt);
            }
        });

        btn_chonAnh.setText("Chọn hình");
        btn_chonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonAnhActionPerformed(evt);
            }
        });
        btn_chonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileDialog = new FileDialog((Frame) null, "Chọn hình", FileDialog.LOAD);
                fileDialog.setVisible(true);
                String fileName = fileDialog.getFile();
                if (fileName != null) {
                    btn_chonAnh.setText(fileName);
                    //					frm_ThongTin.add(lblTenHinhDuocChon);
                    //					int kichThuoc = lblTenHinhDuocChon.getText().length() * (85 / 13);
                    //					kichThuocTen = Box.createHorizontalStrut(kichThuoc);
                    //					frm_ThongTin.add(kichThuocTen);
                }
            }
        });

        javax.swing.GroupLayout frm_ThongTinLayout = new javax.swing.GroupLayout(frm_ThongTin);
        frm_ThongTin.setLayout(frm_ThongTinLayout);
        frm_ThongTinLayout.setHorizontalGroup(
            frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_ThongTinLayout.createSequentialGroup()
                        .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_LoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_maPhong, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_tenPhong, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbo_trangThaiPhong, javax.swing.GroupLayout.Alignment.LEADING, 0, 220, Short.MAX_VALUE))
                            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                                .addComponent(txt_dienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_soGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rad_coGiuongPhu)
                            .addComponent(btn_chonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(frm_ThongTinLayout.createSequentialGroup()
                        .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(rad_coHutThuoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rad_khongGiuongPhu)
                                    .addComponent(rad_khongHutThuoc))))
                        .addContainerGap())))
        );
        frm_ThongTinLayout.setVerticalGroup(
            frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_maPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(cbo_trangThaiPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(cbo_LoaiPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_dienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(cbo_soGiuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rad_coGiuongPhu)
                        .addComponent(rad_khongGiuongPhu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rad_coHutThuoc)
                    .addComponent(rad_khongHutThuoc))
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_ThongTinLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14))
                    .addGroup(frm_ThongTinLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_chonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );

        jPanel4.add(frm_ThongTin, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(350, 180));

        btnThem.setText("Thêm Phòng");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnXoaRong.setText("Xóa Rỗng");
        btnXoaRong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaRongMouseClicked(evt);
            }
        });

        btnCapNhat.setText("Cập Nhật Phòng");
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoaRong, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(182, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnXoaRong, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(108, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        search_Engine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search_Engine.setLayout(new javax.swing.BoxLayout(search_Engine, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setPreferredSize(new java.awt.Dimension(386, 50));

        txt_timKiem.setText("Tên Phòng");
        txt_timKiem.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mã nhân viên...");
        txt_timKiem.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon(getClass().getResource("/icon/search_1.svg")));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        search_Engine.add(jPanel6);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BASIC", "DOUBLE", "STANDARD", "BUSINESS","VIP" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Trạng Thái Phòng:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có", "Không" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Giường Phụ:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "UNAVAILABLE", "BOOKED", "OCCUPIED"}));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Loại Phòng:");
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 16));

        btn_search.setText("Tìm Kiếm");
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        search_Engine.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        search_Engine.add(jPanel8);

        add(search_Engine, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void rad_hoanTraKhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_hoanTraKhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_hoanTraKhongActionPerformed

    private void btn_search1MouseClicked(java.awt.event.MouseEvent evt) {
    }

    private void btn_search1ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void tbl_PhongOMouseEntered(java.awt.event.MouseEvent evt) {
    }
///

    public void DeleteForm() {
        txt_maPhong.setText("");
        txt_maPhong.setEnabled(true);
        txt_maPhong.requestFocus();

        txt_tenPhong.setText("");

        cbo_trangThaiPhong.setSelectedItem("AVAILABLE");
        cbo_LoaiPhong.setSelectedItem("BASIC");
        cbo_soGiuong.setSelectedItem("0");

        rad_coHutThuoc.setSelected(true);
        rad_khongHutThuoc.setSelected(false);

        rad_coGiuongPhu.setSelected(true);
        rad_khongGiuongPhu.setSelected(false);

        txt_dienTich.setText("");
        txt_View.setText("");

    }

    private void AllListPhong() throws SQLException {
        tbl_PhongO.removeAll();
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        ph_DAO = new Phong_DAO();
        ArrayList<Phong> listSP = ph_DAO.getAllTablePhong();
        for (Phong sp : listSP) {

            Boolean isGiuongPhu = sp.isGiuongPhu();
            String giuongPhu;
            if (isGiuongPhu) {
                giuongPhu = "Có";
            } else {
                giuongPhu = "Không";
            }

            Boolean isHutThuoc = sp.isHutThuoc();
            String hutThuoc;
            if (isHutThuoc) {
                hutThuoc = "Có";
            } else {
                hutThuoc = "Không";
            }
            modelPhong.addRow(new Object[]{sp.getMaPhong(), sp.getTenPhong(), sp.getLoaiPhong(), sp.getTrangThaiPhong(), sp.getDienTich(), sp.getSoGiuong(), giuongPhu, sp.getView(), hutThuoc, getIcon(sp.getHinhAnhPhong(), 60, 50)});
        }
    }
    private void rad_loaiDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_loaiDoUongActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_rad_loaiDoUongActionPerformed

    private void rad_trangThaiConSuDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_trangThaiConSuDungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_trangThaiConSuDungActionPerformed

    private void rad_hoanTraChoPhepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_hoanTraChoPhepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_hoanTraChoPhepActionPerformed

    private void tbl_PhongOMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here
        int rowSelection = tbl_PhongO.getSelectedRow();

        if (rowSelection >= 0 && rowSelection < tbl_PhongO.getRowCount()) {
            txt_maPhong.setText(tbl_PhongO.getValueAt(rowSelection, 0).toString());
            txt_maPhong.setEnabled(false);
            txt_tenPhong.setText(tbl_PhongO.getValueAt(rowSelection, 1).toString());

            String loaiPhong = tbl_PhongO.getValueAt(rowSelection, 2).toString();
            cbo_LoaiPhong.setSelectedItem(loaiPhong);

            String trangThaiPhong = tbl_PhongO.getValueAt(rowSelection, 3).toString();
            cbo_trangThaiPhong.setSelectedItem(trangThaiPhong);

            txt_dienTich.setText(tbl_PhongO.getValueAt(rowSelection, 4).toString());

            String soGiuong = tbl_PhongO.getValueAt(rowSelection, 5).toString();
            cbo_soGiuong.setSelectedItem(soGiuong);

            String giuongPhu = tbl_PhongO.getValueAt(rowSelection, 6).toString();

            if (giuongPhu.contains("Có")) {
                rad_coGiuongPhu.setSelected(true);
                rad_khongGiuongPhu.setSelected(false);
            } else {
                rad_coGiuongPhu.setSelected(false);
                rad_khongGiuongPhu.setSelected(true);
            }

            txt_View.setText(tbl_PhongO.getValueAt(rowSelection, 7).toString());

            String hutThuoc = tbl_PhongO.getValueAt(rowSelection, 8).toString();

            if (hutThuoc.contains("Có")) {
                rad_coHutThuoc.setSelected(true);
                rad_khongHutThuoc.setSelected(false);
            } else {
                rad_coHutThuoc.setSelected(false);
                rad_khongHutThuoc.setSelected(true);
            }

            String filePath;
            try {
                Phong p = ph_DAO.findPhongByMa(tbl_PhongO.getValueAt(rowSelection, 0).toString());
                filePath = p.getHinhAnhPhong();
                File file = new File(filePath);
                String fileName = file.getName(); // Lấy tên tệp
                btn_chonAnh.setText(fileName);
            } catch (Exception e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }

        } else {
            System.out.println("Lỗi nè! tbl_PhongOMouseClicked()");
        }

    }

    private void txt_giaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_giaNhapActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_giaNhapActionPerformed

    private void rad_trangThaiHetHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_trangThaiHetHanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_trangThaiHetHanActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void rad_loaiDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_loaiDoUongMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_rad_loaiDoUongMouseClicked

    private void rad_loaiDoAnLienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_loaiDoAnLienMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_rad_loaiDoAnLienMouseClicked

    private void rad_trangThaiConSuDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_trangThaiConSuDungMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_rad_trangThaiConSuDungMouseClicked

    private void rad_trangThaiKhongSuDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_trangThaiKhongSuDungMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_rad_trangThaiKhongSuDungMouseClicked

    private void rad_trangThaiHetHanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_trangThaiHetHanMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_rad_trangThaiHetHanMouseClicked

    private void rad_hoanTraChoPhepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_hoanTraChoPhepMouseClicked
//        // TODO add your handling code here:

    }//GEN-LAST:event_rad_hoanTraChoPhepMouseClicked

    private void rad_hoanTraKhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_hoanTraKhongMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_rad_hoanTraKhongMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnXoaActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btn_searchActionPerformed

    private void btnXoaRongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaRongMouseClicked
        // TODO add your handling code here:
        DeleteForm();
    }//GEN-LAST:event_btnXoaRongMouseClicked

    private boolean isvalid() {
        // Validate tên phòng
        if (!txt_tenPhong.getText().matches("^P\\d+$")) {
            JOptionPane.showMessageDialog(null, "Tên phòng phải bắt đầu bằng chữ 'P' và các ký tự còn lại là số.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate diện tích
        Double dienTich = null;
        try {
            dienTich = Double.valueOf(txt_dienTich.getText());
            if (dienTich < 0) {
                JOptionPane.showMessageDialog(null, "Diện tích không được âm.", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Diện tích phải là một số hợp lệ.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        String imageSelect = btn_chonAnh.getText().trim();
        if (imageSelect.equals("Chọn hình")) {
            JOptionPane.showMessageDialog(this, "Hãy chọn ảnh" + "");
            return false;
        }

        // Nếu tất cả các điều kiện được thỏa mãn
        return true;
    }


    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        int rowChoice = tbl_PhongO.getSelectedRow();

        if (isvalid()) {
//            String maPhong = generateRoomID();
            String maPhong = txt_maPhong.getText();
//            txt_maPhong.setEditable(false);
            String tenPhong = txt_tenPhong.getText();
            Double dienTich = Double.valueOf(txt_dienTich.getText());
            String hinh = btn_chonAnh.getText().toString();
            String hinhAnh = "data/images/" + hinh;
            String view = txt_View.getText();

            String isGiuongPhu = null;
            Boolean GiuongPhu = null;
            if (rad_coGiuongPhu.isSelected()) {
                isGiuongPhu = "Có";
                GiuongPhu = true;
                rad_coGiuongPhu.setSelected(true);
                rad_khongGiuongPhu.setSelected(false);
            } else {
                isGiuongPhu = "Không";
                GiuongPhu = false;
                rad_coGiuongPhu.setSelected(false);
                rad_khongGiuongPhu.setSelected(true);
            }

            String isHutThuoc = null;
            Boolean hutThuoc = null;
            if (rad_coHutThuoc.isSelected()) {
                isHutThuoc = "Có";
                hutThuoc = true;
                rad_coHutThuoc.setSelected(true);
                rad_khongHutThuoc.setSelected(false);
            } else {
                isHutThuoc = "Không";
                hutThuoc = false;
                rad_coHutThuoc.setSelected(false);
                rad_khongHutThuoc.setSelected(true);
            }

//        TrangThaiPhong trangThaiPhong = (TrangThaiPhong) cbo_trangThaiPhong.getSelectedItem();
            TrangThaiPhong trangThaiPhong = TrangThaiPhong.valueOf(cbo_trangThaiPhong.getSelectedItem().toString());

            Integer soGiuong = cbo_soGiuong.getSelectedIndex();

            LoaiPhong loaiPhong = LoaiPhong.valueOf(cbo_LoaiPhong.getSelectedItem().toString());

            Phong sp = new Phong(maPhong, tenPhong, dienTich, soGiuong, GiuongPhu, view, hutThuoc, "data/images/" + hinh, loaiPhong, trangThaiPhong);

// Update
            try {
                ph_DAO.createPhong(sp);

                if (tbl_PhongO.getModel() == null) {
                    String[] arr = {"Mã Phòng", "Tên Phòng", "Loại Phòng", "Trạng Thái Phòng", "Diện Tích Phòng", "Số Giường", "Giường Phụ", "View", "Hút Thuốc",
                        "Hình Ảnh Phòng"};
                    DefaultTableModel modelPhongO = new DefaultTableModel(arr, 0);
                    tbl_PhongO.setModel(modelPhongO);
                }
                DefaultTableModel modelPhongO = (DefaultTableModel) tbl_PhongO.getModel();

                modelPhongO.addRow(new Object[]{maPhong, tenPhong, cbo_LoaiPhong.getSelectedItem().toString(), cbo_trangThaiPhong.getSelectedItem().toString(), dienTich, soGiuong, isGiuongPhu, view, isHutThuoc, getIcon(hinhAnh, 60, 50)});
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi nè 1!! btnThemActionPerformed()");

            }

            DeleteForm();
        } else {
            System.out.println("Thêm phòng lỗi");
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void rad_khongGiuongPhuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_khongGiuongPhuMouseClicked
        // TODO add your handling code here:
        rad_coGiuongPhu.setSelected(false);
        rad_khongGiuongPhu.setSelected(true);
    }//GEN-LAST:event_rad_khongGiuongPhuMouseClicked

    private void rad_coGiuongPhuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_coGiuongPhuMouseClicked
        // TODO add your handling code here:
        rad_coGiuongPhu.setSelected(true);
        rad_khongGiuongPhu.setSelected(false);
    }//GEN-LAST:event_rad_coGiuongPhuMouseClicked

    private void rad_coHutThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_coHutThuocMouseClicked
        // TODO add your handling code here:
        rad_coHutThuoc.setSelected(true);
        rad_khongHutThuoc.setSelected(false);

    }//GEN-LAST:event_rad_coHutThuocMouseClicked

    private void rad_khongHutThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rad_khongHutThuocMouseClicked
        // TODO add your handling code here:
        rad_coHutThuoc.setSelected(false);
        rad_khongHutThuoc.setSelected(true);

    }//GEN-LAST:event_rad_khongHutThuocMouseClicked

//    private static int currentFloor = 1;
//    private static int currentRoomNumber = 1;
//    private static String generateRoomID() {
//        String floor = String.format("%02d", currentFloor);
//        String roomNumber = String.format("%02d", currentRoomNumber);
//
//        // Tăng số phòng và tầng nếu cần
//        currentRoomNumber++;
//        if (currentRoomNumber > 99) {
//            currentRoomNumber = 1;
//            currentFloor++;
//            if (currentFloor > 15) {
//                currentFloor = 1; // Reset tầng về 1 nếu vượt quá 15
//            }
//        }
//
//        return floor + roomNumber;
//    }
    private ImageIcon getIcon(String path, int width, int height) {
        // TODO Auto-generated method stub
        ImageIcon iconEmployee = new ImageIcon(path);
        Image scaledImage = iconEmployee.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        return scaledIcon;
    }

    private void btnCapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseClicked
        // TODO add your handling code here:
        if (isvalid()) {
            int rowChoice = tbl_PhongO.getSelectedRow();

            String maPhong = txt_maPhong.getText();
            txt_maPhong.setEditable(false);
            String tenPhong = txt_tenPhong.getText();
            Double dienTich = Double.valueOf(txt_dienTich.getText());
            String hinh = btn_chonAnh.getText().toString();
            String view = txt_View.getText();

            String isGiuongPhu = null;
            Boolean GiuongPhu = null;
            if (rad_coGiuongPhu.isSelected()) {
                isGiuongPhu = "Có";
                GiuongPhu = true;
                rad_coGiuongPhu.setSelected(true);
                rad_khongGiuongPhu.setSelected(false);
            } else {
                isGiuongPhu = "Không";
                GiuongPhu = false;
                rad_coGiuongPhu.setSelected(false);
                rad_khongGiuongPhu.setSelected(true);
            }

            String isHutThuoc = null;
            Boolean hutThuoc = null;
            if (rad_coHutThuoc.isSelected()) {
                isHutThuoc = "Có";
                hutThuoc = true;
                rad_coHutThuoc.setSelected(true);
                rad_khongHutThuoc.setSelected(false);
            } else {
                isHutThuoc = "Không";
                hutThuoc = false;
                rad_coHutThuoc.setSelected(false);
                rad_khongHutThuoc.setSelected(true);
            }

            TrangThaiPhong trangThaiPhong = TrangThaiPhong.valueOf(cbo_trangThaiPhong.getSelectedItem().toString());
            Integer soGiuong = cbo_soGiuong.getSelectedIndex();
            LoaiPhong loaiPhong = LoaiPhong.valueOf(cbo_LoaiPhong.getSelectedItem().toString());
            Phong sp = new Phong(maPhong, tenPhong, dienTich, soGiuong, GiuongPhu, view, hutThuoc, "data/images/" + hinh, loaiPhong, trangThaiPhong);

            // Update 
            try {
                System.out.println("gui.JPanel_QuanLyPhongO.btnCapNhatMouseClicked()" + trangThaiPhong);
                if ("AVAILABLE".equals(trangThaiPhong.getTenTrangThai()) || "UNAVAILABLE".equals(trangThaiPhong.getTenTrangThai())) {
                    JOptionPane.showMessageDialog(null, "Không thể sửa nếu phòng đang được thuê hoặc dặt trước");

                } else {
                    ph_DAO.updatePhong(sp);

                    if (tbl_PhongO.getModel() == null) {
                        String[] arr = {"Mã Phòng", "Tên Phòng", "Loại Phòng", "Trạng Thái Phòng", "Diện Tích Phòng", "Số Giường", "Giường Phụ", "View", "Hút Thuốc",
                            "Hình Ảnh Phòng"};
                        DefaultTableModel modelPhongO = new DefaultTableModel(arr, 0);
                        tbl_PhongO.setModel(modelPhongO);
                    }
                    DefaultTableModel modelPhongO = (DefaultTableModel) tbl_PhongO.getModel();

                    modelPhongO.setValueAt(maPhong, rowChoice, 0);
                    modelPhongO.setValueAt(tenPhong, rowChoice, 1);
                    modelPhongO.setValueAt(cbo_LoaiPhong.getSelectedItem().toString(), rowChoice, 2);
                    modelPhongO.setValueAt(cbo_trangThaiPhong.getSelectedItem().toString(), rowChoice, 3);
                    modelPhongO.setValueAt(dienTich, rowChoice, 4);
                    modelPhongO.setValueAt(soGiuong, rowChoice, 5);
                    modelPhongO.setValueAt(isGiuongPhu, rowChoice, 6);

                    modelPhongO.setValueAt(view, rowChoice, 7);
                    modelPhongO.setValueAt(isHutThuoc, rowChoice, 8);
                    modelPhongO.setValueAt(hinh, rowChoice, 9);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi nè 1!! btnCapNhatActionPerformed()");

            }

            DeleteForm();
        }


    }//GEN-LAST:event_btnCapNhatMouseClicked

    private void btn_chonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonAnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_chonAnhActionPerformed

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (txt_timKiem.getText().equals("")) {
            try {
                AllListPhong();
            } catch (SQLException ex) {
                Logger.getLogger(JPanel_QuanLyPhongO.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        try {
            try {
                ConnectDB.getInstance().connect();
                String timkiem = txt_timKiem.getText().toLowerCase();

                // Xóa toàn bộ dữ liệu trong tbl_QL_NhanVien
                DefaultTableModel model = (DefaultTableModel) tbl_PhongO.getModel();
                model.setRowCount(0);

                ph_DAO = new Phong_DAO();
                ArrayList<Phong> listSP = ph_DAO.getPhongTheoTenPhong(timkiem); // Retrieve data based on the text field

                if (model.getColumnCount() == 0) {
                    String[] arr = {"Mã Phòng", "Tên Phòng", "Loại Phòng", "Trạng Thái Phòng", "Diện Tích Phòng", "Số Giường", "Giường Phụ", "View", "Hút Thuốc", "Hình Ảnh Phòng"};
                    model.setColumnIdentifiers(arr);
                }

                // Filter the data based on user input
                for (Phong sp : listSP) {
                    // Add row if it matches all provided filters
                    Boolean isGiuongPhu = sp.isGiuongPhu();
                    String giuongPhu = isGiuongPhu ? "Có" : "Không";

                    Boolean isHutThuoc = sp.isHutThuoc();
                    String hutThuoc = isHutThuoc ? "Có" : "Không";

                    model.addRow(new Object[]{sp.getMaPhong(), sp.getTenPhong(), sp.getLoaiPhong(), sp.getTrangThaiPhong(), sp.getDienTich(), sp.getSoGiuong(), giuongPhu, sp.getView(), hutThuoc, getIcon(sp.getHinhAnhPhong(), 60, 50)});
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            // TODO add your handling code here:
            AllListPhong();
        } catch (SQLException ex) {
            Logger.getLogger(JPanel_QuanLyPhongO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoaRong;
    private javax.swing.JButton btn_chonAnh;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cbo_LoaiPhong;
    private javax.swing.JComboBox<String> cbo_soGiuong;
    private javax.swing.JComboBox<String> cbo_trangThaiPhong;
    private javax.swing.JPanel frm_ThongTin;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rad_coGiuongPhu;
    private javax.swing.JRadioButton rad_coHutThuoc;
    private javax.swing.JRadioButton rad_khongGiuongPhu;
    private javax.swing.JRadioButton rad_khongHutThuoc;
    private javax.swing.JPanel search_Engine;
    private javax.swing.JTable tbl_PhongO;
    private javax.swing.JTextArea txt_View;
    private javax.swing.JTextField txt_dienTich;
    public javax.swing.JTextField txt_maPhong;
    private javax.swing.JTextField txt_tenPhong;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object o = e.getSource();
        if (o.equals(btn_search)) {
            System.out.println("Phòng Ở oke oke!!");
        }
    }

    public void addEvents() {
        btn_search.addActionListener(this);

    }
}
