/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.awt.Color;
import java.awt.Font;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import connectDB.ConnectDB;
import dao.NhanVien_DAO;
import dao.TaiKhoan_DAO;
import entity.NhanVien;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M S I
 */
public class JPanel_QuanLyNhanVien extends javax.swing.JPanel implements ActionListener, MouseListener {

    private String id;
    private TaiKhoan_DAO tk_dao;

    /**
     * Creates new form JPanel_QuanLyNhanVien
     */
    public JPanel_QuanLyNhanVien() throws SQLException {
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
        }
        initComponents();
        addEvents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NhanVien = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        frm_ThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txt_Ten = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        rd_nu = new javax.swing.JRadioButton();
        rd_nam = new javax.swing.JRadioButton();
        rd_nghi = new javax.swing.JRadioButton();
        rd_lam = new javax.swing.JRadioButton();
        rd_lt = new javax.swing.JRadioButton();
        rd_ql = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Rong = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        search_Engine = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txt_maCanTim = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        cb_gt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cb_cv = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_tt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_Loc = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(931, 800));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));
        jPanel3.setLayout(new java.awt.BorderLayout());

        String[] colHeader = {"Mã nhân viên", "Họ và Tên", "Giới tính", "Địa chỉ", "Trạng Thái Làm Việc", "Số Điện Thoại", "Chức Vụ"};
        modelNhanVien = new DefaultTableModel(colHeader, 0);
        tbl_NhanVien.setModel(modelNhanVien);
        jScrollPane1.setViewportView(tbl_NhanVien);
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        tbl_NhanVien.getColumnModel().getColumn(1).setCellRenderer(leftRenderer);

        // Tạo renderer để căn trái cho cột thứ 6
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        // Căn giữa các cột cụ thể
        tbl_NhanVien.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbl_NhanVien.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tbl_NhanVien.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tbl_NhanVien.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tbl_NhanVien.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        tbl_NhanVien.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel11.setBackground(new java.awt.Color(51, 255, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Danh Sách Thông Tin Nhân Viên");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setMaximumSize(new java.awt.Dimension(270, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(270, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(265, 25));
        jPanel3.add(jLabel11, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        frm_ThongTin.setPreferredSize(new java.awt.Dimension(350, 0));

        jLabel1.setText("Mã:");

        jLabel2.setText("Giới tính:");

        jLabel6.setText("Tên:");

        jLabel7.setText("Địa chỉ:");

        jLabel8.setText("SĐT:");

        jLabel9.setText("Trạng Thái:");

        jLabel10.setText("Chức vụ:");

        txtMaNV.setEditable(false);
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        rd_nu.setText("Nữ");

        rd_nam.setText("Nam");
        rd_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_namActionPerformed(evt);
            }
        });

        rd_nghi.setText("Đã nghỉ");

        rd_lam.setText("Đang làm");
        rd_lam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_lamActionPerformed(evt);
            }
        });

        rd_lt.setText("Lễ Tân");
        rd_lt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_ltActionPerformed(evt);
            }
        });

        rd_ql.setText("Quản lý");

        javax.swing.GroupLayout frm_ThongTinLayout = new javax.swing.GroupLayout(frm_ThongTin);
        frm_ThongTin.setLayout(frm_ThongTinLayout);
        frm_ThongTinLayout.setHorizontalGroup(
            frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_ThongTinLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frm_ThongTinLayout.createSequentialGroup()
                        .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                                .addComponent(rd_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rd_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_Ten)
                            .addComponent(txtMaNV)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frm_ThongTinLayout.createSequentialGroup()
                        .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                                .addComponent(rd_lam, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rd_nghi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_SDT)
                            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                                .addComponent(rd_lt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rd_ql, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_ThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        frm_ThongTinLayout.setVerticalGroup(
            frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_ThongTinLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_nu)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_nam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_nghi)
                    .addComponent(rd_lam)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frm_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_lt)
                    .addComponent(rd_ql))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        gr_gt.add(rd_nam);gr_gt.add(rd_nu);
        gr_tt.add(rd_lam);gr_tt.add(rd_nghi);
        gr_cv.add(rd_lt);gr_cv.add(rd_ql);

        jPanel4.add(frm_ThongTin, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(350, 160));

        btnThem.setText("Thêm");
        btnThem.setToolTipText("");
        btnThem.setBackground(new Color(0, 102, 102));
        btnThem.setForeground(Color.WHITE);
        btnThem.setFont(new Font("Roboto Mono Medium", Font.PLAIN, 16));

        btn_Xoa.setText("Danh Sách Đen");
        btn_Xoa.setBackground(new Color(0, 102, 102));
        btn_Xoa.setForeground(Color.WHITE);
        btn_Xoa.setFont(new Font("Roboto Mono Medium", Font.PLAIN, 16));

        btn_Sua.setText("Cập nhật");
        btn_Sua.setBackground(new Color(0, 102, 102));
        btn_Sua.setForeground(Color.WHITE);
        btn_Sua.setFont(new Font("Roboto Mono Medium", Font.PLAIN, 16));

        btn_Rong.setText("Xóa rỗng");
        btn_Rong.setBackground(new Color(0, 102, 102));
        btn_Rong.setForeground(Color.WHITE);
        btn_Rong.setFont(new Font("Roboto Mono Medium", Font.PLAIN, 16));
        btn_Rong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Rong, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Rong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel4.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        search_Engine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search_Engine.setLayout(new javax.swing.BoxLayout(search_Engine, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setPreferredSize(new java.awt.Dimension(386, 50));

        txt_maCanTim.setText("");
        txt_maCanTim.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mã nhân viên...");
        txt_maCanTim.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("./icon/search_1.svg"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(txt_maCanTim, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(txt_maCanTim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        search_Engine.add(jPanel6);

        cb_gt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Nam", "Nữ"}));
        cb_gt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_gtActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Trạng Thái:");

        cb_cv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả","Lễ Tân","Quản Lý"}));
        cb_cv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cvActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Chức vụ");

        cb_tt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang làm", "Đã nghỉ"}));
        cb_tt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ttActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Giới tính:");
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 16));

        btn_Loc.setText("Lọc");

        btn_refresh.setIcon(new FlatSVGIcon("./icon/reload.svg"));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cb_tt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(cb_cv, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Loc, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_tt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_cv, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        search_Engine.add(jPanel7);

        add(search_Engine, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_cvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_cvActionPerformed

    private void cb_gtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_gtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_gtActionPerformed

    private void cb_ttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_ttActionPerformed

    private void rd_lamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_lamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_lamActionPerformed

    private void btn_RongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RongActionPerformed

    private void rd_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_namActionPerformed

    private void rd_ltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_ltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_ltActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    public javax.swing.JButton btn_Loc;
    private javax.swing.JButton btn_Rong;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Xoa;
    public javax.swing.JButton btn_refresh;
    private javax.swing.JComboBox<String> cb_cv;
    private javax.swing.JComboBox<String> cb_gt;
    private javax.swing.JComboBox<String> cb_tt;
    private javax.swing.JPanel frm_ThongTin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rd_lam;
    private javax.swing.JRadioButton rd_lt;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nghi;
    private javax.swing.JRadioButton rd_nu;
    private javax.swing.JRadioButton rd_ql;
    private javax.swing.JPanel search_Engine;
    private javax.swing.JTable tbl_NhanVien;
    public javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_Ten;
    private javax.swing.JTextField txt_maCanTim;
    // End of variables declaration//GEN-END:variables
    private NhanVien_DAO nv_dao = new NhanVien_DAO();
    private DefaultTableModel modelNhanVien;
    javax.swing.ButtonGroup gr_gt = new javax.swing.ButtonGroup();
    javax.swing.ButtonGroup gr_tt = new javax.swing.ButtonGroup();
    javax.swing.ButtonGroup gr_cv = new javax.swing.ButtonGroup();

    public NhanVien taoNV() {
        String ma = txtMaNV.getText().toString();
        String ten = txt_Ten.getText().toString();
        boolean gioiTinh = rd_nam.isSelected();
        String diaChi = txt_DiaChi.getText().toString();
        boolean trangThai = rd_lam.isSelected();
        String sdt = txt_SDT.getText().toString();
        boolean chucVu = rd_ql.isSelected();
        return new NhanVien(ma, ten, gioiTinh, diaChi, trangThai, sdt, "null", chucVu);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object o = e.getSource();
        if (o.equals(btn_Xoa)) {
            int row = tbl_NhanVien.getSelectedRow();
            String ma = tbl_NhanVien.getValueAt(row, 0).toString();
            nv_dao.updateTrangThaiLamViec(ma);
            delData();
            try {
                loadData();
            } catch (SQLException ex) {
                Logger.getLogger(JPanel_QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (o.equals(btnThem)) {
            if (kiemTraCuPhap()) {
                NhanVien nv = taoNV();
                String gt = "";
                String tt = "";
                String cv = "";
                genID(nv);
                nv.setMaNhanVien(id);
                tk_dao = new TaiKhoan_DAO();

                modelNhanVien.addRow(new Object[]{nv.getMaNhanVien(), nv.getHoTenNhanVien(), gt = nv.isGioiTinh() ? "Nam" : "Nữ",
                    nv.getDiaChi(), tt = nv.isTrangThaiLamViec() ? "Đang làm" : "Đã nghỉ", nv.getSoDIenThoai(), cv = nv.isChucVu() ? "Quản lý" : "Lễ Tân"});
                try {
                    String imagePath_relative = "/gui/emp_pic/" + nv.getMaNhanVien() + ".png";
                    nv.setHinhAnh("/gui/emp_pic/" + nv.getMaNhanVien() + ".png");
                    nv_dao.createNhanVien(nv);
                    try {
                        tk_dao.taoTaiKhoan(nv.getMaNhanVien(), nv.getSoDIenThoai());
                    } catch (SQLException ex) {
                        Logger.getLogger(JPanel_QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(JPanel_QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (o.equals(btn_Loc)) {
            try {
                ArrayList<NhanVien> list;
                if (txt_maCanTim.getText().equals("")) {
                    list = nv_dao.getAllTableNhanVien();
                    delData();
                } else {
                    list = nv_dao.getNhanVienTheoMa(txt_maCanTim.getText());
                    delData();
                }
                System.out.println(list);

                String gt = "";
                String tt = "";
                String cv = "";
                for (NhanVien nv : list) {
                    modelNhanVien.addRow(new Object[]{
                        nv.getMaNhanVien(),
                        nv.getHoTenNhanVien(),
                        gt = nv.isGioiTinh() ? "Nam" : "Nữ",
                        nv.getDiaChi(),
                        tt = nv.isTrangThaiLamViec() ? "Đang làm" : "Đã nghỉ",
                        nv.getSoDIenThoai(),
                        cv = nv.isChucVu() ? "Quản lý" : "Lễ Tân"
                    });
                }
                for (int i = 0; i < tbl_NhanVien.getRowCount(); i++) {
                    if (cb_gt.getSelectedIndex() == 1 && !tbl_NhanVien.getValueAt(i, 2).toString().equals("Nam")) {
                        modelNhanVien.removeRow(i);
                        i--;
                    }
                    if (cb_gt.getSelectedIndex() == 2 && tbl_NhanVien.getValueAt(i, 2).toString().equals("Nam")) {
                        modelNhanVien.removeRow(i);
                        i--;
                    }
                }
                for (int i = 0; i < tbl_NhanVien.getRowCount(); i++) {
                    if (cb_tt.getSelectedIndex() == 1 && tbl_NhanVien.getValueAt(i, 4).toString().equals("Đã nghỉ")) {
                        modelNhanVien.removeRow(i);
                        i--;
                    }
                    if (cb_tt.getSelectedIndex() == 2 && !tbl_NhanVien.getValueAt(i, 4).toString().equals("Đã nghỉ")) {
                        modelNhanVien.removeRow(i);
                        i--;
                    }
                }
                for (int i = 0; i < tbl_NhanVien.getRowCount(); i++) {
                    if (cb_tt.getSelectedIndex() == 1 && tbl_NhanVien.getValueAt(i, 4).toString().equals("Đã nghỉ")) {
                        modelNhanVien.removeRow(i);
                        i--;
                    }
                    if (cb_tt.getSelectedIndex() == 2 && !tbl_NhanVien.getValueAt(i, 4).toString().equals("Đã nghỉ")) {
                        modelNhanVien.removeRow(i);
                        i--;
                    }
                }
                for (int i = 0; i < tbl_NhanVien.getRowCount(); i++) {
                    if (cb_cv.getSelectedIndex() == 1 && tbl_NhanVien.getValueAt(i, 6).toString().equals("Quản lý")) {
                        modelNhanVien.removeRow(i);
                        i--;
                    }
                    if (cb_cv.getSelectedIndex() == 2 && !tbl_NhanVien.getValueAt(i, 6).toString().equals("Quản lý")) {
                        modelNhanVien.removeRow(i);
                        i--;
                    }
                }
                if (tbl_NhanVien.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Không tìm thấy!",
                            "Thông báo không tìm thấy",
                            JOptionPane.WARNING_MESSAGE
                    );
                    modelNhanVien.setRowCount(0);
                    this.revalidate();
                    this.repaint();
                }
            } catch (IOException ex) {
                Logger.getLogger(JPanel_QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JPanel_QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (o.equals(btn_Rong)) {
            txtMaNV.setText("");
            txt_Ten.setText("");
            rd_nam.setSelected(true);
            txt_DiaChi.setText("");
            rd_lam.setSelected(true);
            txt_SDT.setText("");
            rd_lt.setSelected(true);
        }
        if (o.equals(btn_refresh)) {
            delData();
            try {
                loadData();
            } catch (SQLException ex) {
                Logger.getLogger(JPanel_QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (o.equals(btn_Sua)) {
            int selectedRow = tbl_NhanVien.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một nhân viên để sửa.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (kiemTraCuPhap()) {
                NhanVien new_nv = taoNV();
                nv_dao.updateNhanVien(new_nv);
                delData();
                try {
                    loadData();
                } catch (SQLException ex) {
                    Logger.getLogger(JPanel_QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    public void delData() {
        DefaultTableModel dm = (DefaultTableModel) tbl_NhanVien.getModel();
        dm.getDataVector().removeAllElements();
    }

    public boolean kiemTraCuPhap() {
        if (txt_Ten.getText().isEmpty() || !txt_Ten.getText().matches("^([\\p{L}\\s']{2,})+([\\p{L}\\s']{2,})$")) {
            JOptionPane.showMessageDialog(this, "Nhập tên sai cú pháp");
            return false;
        }
        if (txt_SDT.getText().isEmpty() || !txt_SDT.getText().matches("0[1-9]{1}[0-9]{8}")) {
            JOptionPane.showMessageDialog(this, "Nhập số điện thoại sai cú pháp");
            return false;
        }
        return true;
    }

    public void addEvents() {
        btn_refresh.addActionListener(this);
        tbl_NhanVien.addMouseListener(this);
        btnThem.addActionListener(this);
        btn_Xoa.addActionListener(this);
        btn_Rong.addActionListener(this);
        btn_Sua.addActionListener(this);
        btn_Loc.addActionListener(this);
    }

    public void loadData() throws SQLException {
        ArrayList<NhanVien> list = nv_dao.getAllTableNhanVien();
        String gt = "";
        String tt = "";
        String cv = "";
        for (NhanVien nv : list) {
            modelNhanVien.addRow(new Object[]{nv.getMaNhanVien(), nv.getHoTenNhanVien(), gt = nv.isGioiTinh() ? "Nam" : "Nữ",
                nv.getDiaChi(), tt = nv.isTrangThaiLamViec() ? "Đang làm" : "Đã nghỉ", nv.getSoDIenThoai(), cv = nv.isChucVu() ? "Quản lý" : "Lễ Tân"});
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        int row = tbl_NhanVien.getSelectedRow();

        if (row >= 0 && row < tbl_NhanVien.getRowCount()) {
            txtMaNV.setText(modelNhanVien.getValueAt(row, 0).toString());
            txt_Ten.setText(modelNhanVien.getValueAt(row, 1).toString());
            rd_nam.setSelected((modelNhanVien.getValueAt(row, 2) == "Nam"));
            rd_nu.setSelected((modelNhanVien.getValueAt(row, 2) != "Nam"));
            txt_DiaChi.setText(modelNhanVien.getValueAt(row, 3).toString());
            rd_lam.setSelected((modelNhanVien.getValueAt(row, 4) == "Đang làm"));
            rd_nghi.setSelected((modelNhanVien.getValueAt(row, 4) != "Đang làm"));
            txt_SDT.setText(modelNhanVien.getValueAt(row, 5).toString());
            rd_lt.setSelected((modelNhanVien.getValueAt(row, 6) == "Lễ Tân"));
            rd_ql.setSelected((modelNhanVien.getValueAt(row, 6) != "Lễ Tân"));
        }
    }

    public void genID(NhanVien nv) {
        int year = Calendar.getInstance().get(Calendar.YEAR);
        int lastTwoDigitsOfYear = year % 100;
        String yy = String.format("%02d", lastTwoDigitsOfYear);
        int sex = nv.isGioiTinh() ? 1 : 0;
        String s = String.format("%01d", sex);
        int rol = nv.isChucVu() ? 1 : 0;
        String c = String.format("%01d", rol);
        int soLuong = nv_dao.demSoLuongNhanVienTheoMaMau(year);
        String formattedNumber = String.format("%03d", soLuong);
        System.out.println(soLuong);
        id = String.format("NV" + yy + s + c + formattedNumber);
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
